version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - graph-db-data:/pgdata

volumes:
  graph-db-data:
    name: graph-db-data
    external: true