version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - master-db-data:/pgdata

volumes:
  master-db-data:
    name: master-db-data
    external: true