
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: master
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: master
      password: master